# Generated by Django 4.2.1 on 2023-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="context",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ID", models.IntegerField()),
                ("his_period", models.CharField(max_length=50)),
                ("hp_txt_num", models.CharField(max_length=50)),
                ("hp_context", models.TextField()),
            ],
            options={
                "db_table": "context",
                "managed": False,
            },
        ),
    ]
