# Generated by Django 4.2.1 on 2023-05-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kdt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="audio",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "audio",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="context",
        ),
    ]
